connector:
  name: harness-config-repo
  identifier: harnessconfigrepo
  description:
  orgIdentifier: default
  projectIdentifier: onboardingengineertechtest
  type: Github
  spec:
    url: https://github.com/ehardisty/nginx-deployment
    authentication:
      type: Http
      spec:
        type: UsernameToken
        spec:
          username: ehardisty
          tokenRef: githubpat
    apiAccess:
      type: Token
      spec:
        tokenRef: githubpat
    executeOnDelegate: false
    type: Repo
